### ISSUE TITLE
ANCHOR: make sure code is sensible and has inline documentation

### ISSUE THREAD

**Issue by frankiebee** [entropyxyz/cli#102]
- [x] #107
- [ ] [anchor#102 sub issue] then clean up code to match file structure
- [ ] [anchor#102 sub issue] inline docs

**Comment by frankiebee** [comment]
when #107 is close to completion. 
@rh0delta lets address the base class for commonalties and naming schemes

**Comment by frankiebee** [comment]
blocked #107

**Comment by mixmix** [comment]
@frankiebee I think this is done.

Please re-open + add more detail if I got that wrong
