### ISSUE TITLE
[anchor#102 sub issue] start with a better file structure

### ISSUE THREAD

**Issue by frankiebee** [entropyxyz/cli#107]
WIP notes: https://hackmd.io/@naynay/BypjxFrYC/edit

- [x] #208
- [x] #209
- [x] #210
- [ ] #211
- [x] #212

**Comment by mixmix** [comment]
See also : https://github.com/entropyxyz/cli/issues/94

for all the `commands` (flows) groupings

**Comment by frankiebee** [comment]
blocking 102

**Comment by frankiebee** [comment]
- [ ] test
