### ISSUE TITLE
Stop requiring the user to "Select" an account before each process.

### ISSUE THREAD

**Issue by johnnymatthews** [entropyxyz/cli#111]
Currently, to perform any action within the CLI the user must first select the account they want to use. This requires the users to bounce between commands to do what they need to do. For example, say the user has two accounts on the CLI and they want to send funds from one account to the other. This is the process they need to follow:

1. Start the CLI.
2. Select **Manage Accounts**.
3. Select **Select Account**.
4. Choose the account they want to use.
5. Go back to the main menu.
6. Go to **Transfer**.
7. Enter an amount to send.
8. Enter the TO address.
9. Send the funds.

Instead, if we had the user specify what account they want to use for `$this` function, we could eliminated steps 2 through 5:

1. Start the CLI.
1. Go to **Transfer**.
1. Select the `FROM` account.
1. Select to `TO` account.
1. Enter how much to send.
1. Send the funds.

This way of defining which account you want to use also matches the design in https://github.com/entropyxyz/cli/issues/94.

**Comment by mixmix** [comment]
Closing because I think this will be resolved by : https://github.com/entropyxyz/cli/issues/292

Please re-open if I'm wrong
