### ISSUE TITLE
ANCHOR: unit test

### ISSUE THREAD

**Issue by frankiebee** [entropyxyz/cli#120]
requirements for each of these:
- if you need to break functionality out into a function that dosent have inquirer  
- unit tests should test pure functionality and not require "ui" components.
- it's fine for now if you need to pull substrate state 

pairing needed for @rh0delta @mixmix 

Unit Tests needed:
- [x] #125
- [x] #121
- [x] #122
- [x] #123
- [x] #124
- [x] #148
- [x] #149
- [ ] #151
- [x] #150

**Comment by frankiebee** [comment]
blocking #18

**Comment by mixmix** [comment]
Marking this as done because an Anchor TODO which is ... another Anchor is just taking up space in our board
