### ISSUE TITLE
The CLI created an invalid address.

### ISSUE THREAD

**Issue by johnnymatthews** [entropyxyz/cli#132]
This issue is based on a discussion in the Community repo: https://github.com/entropyxyz/community/discussions/54#discussioncomment-9839115

It _looks_ like the CLI was able to generate an address that isn't a valid Substrate address. Based on the screenshot provided in the discussion, the CLI generated `5Equjw221oPGnrNjd3NLEZVYZCiKwtupU8ta1HaubkSsugrr` as an address. When attempting to send funds to that address in the Substrate Portal, the portal complained that the address wasn't valid. Throwing the address into [ss58.org](https://ss58.org/) also suggested that the address is invalid.

- How does the CLI generate addresses?
    - If we're manually creating them, then there might be a problem with our generation method.
    - If we're using Polkadot.js to generate them, there's either something funky with our implementation, or that `.js` package is borked somehow.
- We might want to consider checking that an address is valid before showing it to the user.

**Comment by frankiebee** [comment]
Oh no! This is no good currently we use [polkadot js api's](https://polkadot.js.org/docs/keyring) to generate are address's and secrets

**Comment by frankiebee** [comment]
@rh0delta 
notes:
[example function for validating an address](https://polkadot.js.org/docs/util-crypto/examples/validate-address/)

a possible temporary fix would be to check the address created by polkadot and to warn the user to create a new key? 

this really does require some research. My gut reaction is to tell the user to generate a new seed after initial validation of the address. We might want to look into. Soft deriving a new address from the public key and seeing if that solves this issue without the creation of a new private key.

**Comment by frankiebee** [comment]
@johnnymatthews how was this address grabbed? the address by you posted by the user. When reading the screen shot in the thread: >' https://github.com/entropyxyz/community/discussions/54#discussioncomment-9839115
found the third to last carchter looked like a `q` but what you/them copied has a g.l when i swap that g for a q it's a valid address. did they possibly hand type it out?

**Comment by rh0delta** [comment]
Looks like this issue is based off of an incorrect copy and paste from the user in question, going to close this for now

CC: @frankiebee @johnnymatthews
