### ISSUE TITLE
sign error

### ISSUE THREAD

**Issue by mixmix** [entropyxyz/cli#134]
![image](https://github.com/entropyxyz/cli/assets/2665886/c9bdfdc7-7783-4662-9b12-6e1f93b11471)

Setup:
- node 20, macOS
- fresh install from `main` github [89d45ad](https://github.com/entropyxyz/cli/commit/89d45adc11e30075d25ac292f4f2d43ee9d43688)
- `create account`
- go to `sign`

See this. Is it because we need to register first? Why is it even possible to select sign without registering ...

**Comment by rh0delta** [comment]
this is no longer an issue as of v0.1.0, closing now.
