### ISSUE TITLE
update test-net enpoint to start with `wss`

### ISSUE THREAD

**Issue by frankiebee** [entropyxyz/cli#135]
the test-net endpoint on it's next reboot will be a wss endpoint. 
please write a migration for this

PS: @johnnymatthews registered user accounts will be cleared on network reboot. We'll think up a strategy to maybe handle this in code. but just fyi this will possibly cause bugs for users their keys will also not have balance.

**Comment by johnnymatthews** [comment]
Relevant PR to update docs here: https://github.com/entropyxyz/entropy-docs/pull/144

**Comment by mixmix** [comment]
Closed by https://github.com/entropyxyz/cli/pull/143
