### ISSUE TITLE
Should we move the endpoint to an env var rather than have the endpoint set in the config?

### ISSUE THREAD

**Issue by rh0delta** [entropyxyz/cli#146]
Question came about in the entropy core sync (2024-06-27) where there was a confusion around why the endpoint was not more configurable rather than needing a fair amount of code changes and a new migration to update.

Might make more sense to move the endpoint to an environment variable so that its easily changed, can even look at adding it to secrets manager, but that might be overkill.

**Comment by johnnymatthews** [comment]
I'm all for not hardcoding the network address into the CLI. Can we have both an ENV variable _and_ be able to pass the network in as an argument? That way the user can do either:

```shell
ENTROPY_NETWORK="wss://testnet.entropy.xyz"
entropy-cli --address 05ea ...
```

or

```shell
entropy-cli --network "wss://testnet.entropy.xyz" --address 05ea ...
```

**Comment by rh0delta** [comment]
@johnnymatthews yeah that's definitely a possibility. @frankiebee what are your thoughts on this?

**Comment by frankiebee** [comment]
at one point i laid ground work for this. I see it got removed yes i'm all for this i would still like the ability to have set endpoints in the config though

**Comment by johnnymatthews** [comment]
> at one point i laid ground work for this. I see it got removed

You mean you made commits to fix this issue? They should be around in the history somewhere if so, no?

**Comment by mixmix** [comment]
It's already set-able via ENV:
https://github.com/entropyxyz/cli/blob/dev/src/cli.ts#L25

See some docs-examples:
https://github.com/tj/commander.js/blob/HEAD/examples/options-env.js

**Comment by mixmix** [comment]
In retrospect `ENDPOINT` is a super vague ENV var ... is should def be changed!

**Comment by johnnymatthews** [comment]
> In retrospect ENDPOINT is a super vague ENV var ... is should def be changed!

Agreed. I'd prefer that all environment variables for this CLI start with `ENTROPY_CLI_` or something like that. The `CLI_` bit is specifically to reduce any conflicts with other repos like Core or whatever.

**Comment by rh0delta** [comment]
closing issue, as we are using both an env var and housing the endpoint in the config
