### ISSUE TITLE
ANCHOR: programs

### ISSUE THREAD

**Issue by rh0delta** [entropyxyz/cli#151]
- [x] #152
- [x] #153
- [x] #154
- [x] #155
- [x] #156
- [x] #157

**Comment by frankiebee** [comment]
lets go into more detail here:

This issues is the inital issue for unit tests for "programs" aka are program feature we have now in the tui however the tui and the sdk have got some things wrong and are behind(?) on spec!

what we have "now"
-  `Deploy Program`:
  - `Deploy` 
  - `Get Owned Programs` (implemented incorrectly) these should be  programs you have deployed  
- `User Programs`:
  - `View My Programs` 
  - `Add a Program to My List` 
  - `Remove a Program from My List` 
  - `Check if Program Exists` should not be an option `Get Program Info`
    
 

those options above need their core functions to be broken out and unit tested but also fixed. the fixing

This all brings me to my final point which the above is stupid UX on are part and both those sections should be one 

- [ ] `Programs`
which should give you these options:
  - [ ] `Get Programs for Entropy Account` 
  - [ ] `Add a Program to Entropy Account` 
  - [ ] `Remove a Program from Entropy Account` 
  - [ ] `Get Program Info`
  - [ ] `Deploy Program` 
  - [ ] `Get Deployed Programs` 
  
maybe better language
