### ISSUE TITLE
lets not show users unit8arrays when signing

### ISSUE THREAD

**Issue by frankiebee** [entropyxyz/cli#162]
What am i supposed do with a `console.log`'ed unit 8 array. i want base64 encoded string please as well as the hashing algorithm for the signature so i can do something with it.

**Comment by johnnymatthews** [comment]
Closing this issue will require an update to docs.

**Comment by mixmix** [comment]
Needs documentation PR

**Comment by mixmix** [comment]
@johnnymatthews please make a Docs Issue and close <3
