### ISSUE TITLE
actions vs sessions

### ISSUE THREAD

**Issue by jawndiego** [entropyxyz/cli#20]
the experience in the cli is currently 'action' based and thus fragmented i.e 'transfer action', 'register action' 

there may be users that want an entire flow without traversing the main menu. a flow could look like:  creating a new wallet -> registering -> setting a program -> forming a transaction -> signing -> etc 

at the end of the flow we can then go back to the main menu for specific actions.

**Comment by frankiebee** [comment]
closing in favor of #94
