### ISSUE TITLE
integrate core version bash from sdk to cli for ascii art

### ISSUE THREAD

**Issue by rh0delta** [entropyxyz/cli#202]

**Comment by frankiebee** [comment]
ideally we pull the version directly from the node via the rpc api. however this opens up a whole can of design worms

**Comment by mixmix** [comment]
@rh0delta we aren't pulling from RPC .... is this "done" ?
I have a sneaking suspicion you're relying on a `process.env` right?

**Comment by rh0delta** [comment]
Yeah I'd say this is done
