### ISSUE TITLE
Entropy Balance/Transfer have different units

### ISSUE THREAD

**Issue by mixmix** [entropyxyz/cli#221]
In current refactor I noticed:
- `transfer` takes in `amount` then multiplies by `1e10`  (ten decimal places?)
- `balance` outputs "BITS" ... which is just a BigInt

**Comment by mixmix** [comment]
Requirement:
- programmatic CLI output MUST be easy for other programs to consume
  - :x: `1.10000 TOKENS`
  - :heavy_check_mark: `1.100000`   maybe
  - :heavy_check_mark: `{ amount: 1.00000, unit: 'TOKENS' }`  kinda yuck?

**Comment by rh0delta** [comment]
got confirmation from @JesseAbram, our testnet token name is BITS, which means that the non-human readable number we have been displaying can be formatted to being displayed as a human readable number and the token shorthand is still BITS

i.e 10,000,000,000 BITS = 1 BITS

**Comment by rh0delta** [comment]
I am going to follow how polkadot displays their balances, and use 4 decimal points.
