### ISSUE TITLE
Signing fails if user doesn't have a verifying key set.

### ISSUE THREAD

**Issue by johnnymatthews** [entropyxyz/cli#222]
This is a super silly issue, and you can feel free to close it as `won't fix`, but here's the situation.

1. User installs CLI.
2. Creates account.
3. Funds that account.
4. **Doesn't** register the account.
5. Attempts to sign a message.
6. Gets this error after entering the message:

```shell
verifying key: undefined
Cannot read properties of undefined (reading 'startsWith')
```

Here's the full terminal output:

```shell
? Select Action Sign
? What would you like to do? Sign With Adapter
2024-08-29 10:44:20        REGISTRY: Unknown signed extensions ValidateConfirmRegistered found, treating them as no-effect
2024-08-29 10:44:20        API/INIT: RPC methods not decorated: chainSpec_v1_chainName, chainSpec_v1_genesisHash, chainSpec_v1_properties
? Please choose how you would like to input your message to sign: Text Input
? Enter the message you wish to sign (this will open your default editor): Received
msg to be signed: Sup fam.

verifying key: undefined
Cannot read properties of undefined (reading 'startsWith')
? Return to main menu? (Y/n)
```

Adding a catch to the start of the Signing workflow to see if there's a valid verifying key somewhere could fix this. But again, super low priority issue.

**Comment by mixmix** [comment]
@frankiebee is gonna respond to this
