### ISSUE TITLE
entropy fails to start with an empty config 

### ISSUE THREAD

**Issue by frankiebee** [entropyxyz/cli#245]
side note: always failing now. my guess is because i have an empty config

_Originally posted by @frankiebee in https://github.com/entropyxyz/cli/issues/244#issuecomment-2384338690_
            

We should fail gracefully. This error is not that

```
undefined:1


SyntaxError: Unexpected end of JSON input
```

**Comment by rh0delta** [comment]
@frankiebee retested this on the dev branch and am not running into this error. this may have been silently fixed with the recent changes made.

**Comment by mixmix** [comment]
I think I put a guard in which bars the writing of a bad config.
no guards on read tho
