### ISSUE TITLE
WIP [anchor] Feature completeness

### ISSUE THREAD

**Issue by frankiebee** [entropyxyz/cli#246]
Language:
 - [ ] mostly unified language between cli and tui to the best that we can
   - [ ] "My List" under programs 
- [ ] UNITS:
  - is it token or bits? it should always be tokens `1 Token= 10_000_000_000 BITS` 
    - balance
    - faucet
    - transfer

Scrub out all the warnings from polkadot that are useless
balance errors should never exit execution of the tui

- Should always fail "gracefully" if can. 

Tui:
- [ ] Make account creation/selction the first thing before hitting the action menu see notes: https://hackmd.io/zjE5gEflTDqXe9ZQHJRL9A
- [ ] remove program developer options (make them their own stand alone tui? up for debate)

**Comment by mixmix** [comment]
- Language: https://github.com/entropyxyz/cli/issues/293
- Units: https://github.com/entropyxyz/cli/issues/221
- Polkadot: we've done a round of removing those only remaining ones seem to be disconnection ones
- Fail gracefully: 
- Tui accounts: https://github.com/entropyxyz/cli/issues/292
- Tui remove program developer options : https://github.com/entropyxyz/cli/issues/294

---

closing as have spawned / linked child issues
