### ISSUE TITLE
list env vars for project

### ISSUE THREAD

**Issue by frankiebee** [entropyxyz/cli#256]
In the interests of avoiding naming conflicts, please remember DevOps/SRE/SecOps teams have already been using [this single point of truth to list environment variables](https://github.com/entropyxyz/meta/wiki/Environment-variables#shell-environment-variables) for our other projects and consider consulting and contributing back to this list when you are deciding on environment variable names for your own projects. Thank you.

_Originally posted by @vitropy in https://github.com/entropyxyz/cli/issues/146#issuecomment-2222923755_

**Comment by rh0delta** [comment]
Going to add list items these to the Wiki @vitropy created for the source of truth of all of our environment variables:

```
* `ENTROPY_ENDPOINT` & `ENTROPY_TUI_ENDPOINT`: Websocket endpoint used in the Entropy CLI to create the API instance for use with Polkadot JS.
* `ENTROPY_ACCOUNT`: Address or Alias of Entropy Account used as the default account when the ENTROPY CLI (programmatic interface) or TUI (text interface) is initialized
```

@frankiebee @mixmix please add anything you would like to this and we can update the wiki: https://github.com/entropyxyz/meta/wiki/Environment-variables#shell-environment-variables

**Comment by rh0delta** [comment]
Updated wiki page with env vars used by the CLI, not in conflict with any of the other env vars used within the org. closing issue
