### ISSUE TITLE
TUI / CLI option collisions

### ISSUE THREAD

**Issue by mixmix** [entropyxyz/cli#265]
We recently saw a problem where we wanted to be able to support options for both TUI and Programmatic CLI modes.
The problem is that if you e.g. `.addOption(endopintOption())` at the root and subcommand levels with... then the defaults and parsing of these options collide (see https://github.com/tj/commander.js/issues/2260)

As I see it, we're trending to one of several futures
1. the TUI only runs default config, OR << **we are currently here**
2. the TUI uses differently named options (e.g. `--tui-endpoint`), OR
3. the TUI is subcommand e.g. `entropy tui`, OR
4. the TUI is a different bin-script/ program e.g. `entropy-interactive`

**Comment by rh0delta** [comment]
@mixmix since we have implemented option number 2, going to close this for now.
