### ISSUE TITLE
faucet

### ISSUE THREAD

**Issue by jawndiego** [entropyxyz/cli#28]
in testnet -- we're currently using alice in cli to fund transfers. we'll need to implement a real faucet

**Comment by frankiebee** [comment]
This is no longer accurate but we'll use this issue to track progress on faucet ideas:
currently we are just manually issuing testnet tokens but ideally we have a registered account handle faucet tokens see: https://github.com/entropyxyz/entropy-core/pull/883

this would require a new feature apart of the cli that submits a transaction on chain

**Comment by JesseAbram** [comment]
proposal.......ok what im actually doing for it lol 

- [ ] Launch faucet program to testnet
- [ ] Create one program mod account
- [ ] launch 5 accounts from the program mod key (can add more to scale up) 
- [ ] add faucet as only program on that account 
- [ ]  fund all those accounts 
- [ ] work with @rh0delta to integrate it into cli and maybe then as an adapter into sdk

**Comment by frankiebee** [comment]
> work with @rh0delta to integrate it into cli and maybe then as an adapter into sdk

in my option it would be better as an adapter in the cli then the sdk.
Sdk adapters should be pure formatters for specific chains
the faucet should be a custom adapter that has a `postSign` function that broadcasts to chain(?). However a generic substrate adapter would be nice in the sdk.

**Comment by rh0delta** [comment]
resolved by #133
