### ISSUE TITLE
Input examples shouldn't look like default values.

### ISSUE THREAD

**Issue by johnnymatthews** [entropyxyz/cli#35]
Throughout the CLI the user will encounter examples to show them what they should be entering:

This section from the `Transfer` workflow shows the user that they should enter an integer `(1)`:

```plaintext
? Input amount to transfer: (1)
```

As another example, this section from the `Wallet` workflow shows that the user needs to enter a string `(My Key)`:

```plaintext
? choice: New Key
? Would you like to import a key? No
? name: (My Key)
```

However, the general convention when it comes to CLIs is that the value seen directly next to a question is the _default_ value. By that, I mean that if the user just presses ENTER when asked `? name: (My Key)` the CLI will enter `My Key` as the key name.

A simple solution here is to add `E.g.` at the start of these examples. So the abobe examples would look like:

```plaintext
? Input amount to transfer: (E.g. 1)
```

```plaintext
? choice: New Key
? Would you like to import a key? No
? name: (E.g. My Key)
```

**Comment by rh0delta** [comment]
those values aren't examples, they are the default values for the prompt

**Comment by johnnymatthews** [comment]
They didn't used to be AFAIK, but it seems they are now. Making this as closed.
