### ISSUE TITLE
Custom path for `.entropy-cli.config`

### ISSUE THREAD

**Issue by johnnymatthews** [entropyxyz/cli#47]
By default the `.config` file gets throw into the home `~` directory. It'd be nice to allow the user to set the location of this file to wherever they want (instead of cluttering up the `~/` dir.

**Comment by mixmix** [comment]
see the module npmjs.com/env-paths
it has sane, best pratctice

**Comment by frankiebee** [comment]
quick thoughts on implementation:
- requires migration.
- requires path to be stored somewhere and maybe exported as a global bash var unless we want to ask for path every time or at the beginning of a session

**Comment by mixmix** [comment]
History:
- https://github.com/entropyxyz/cli/pull/88
- https://github.com/entropyxyz/cli/pull/96

These were reverted because we hit some bugs.

**Comment by mixmix** [comment]
Requirements:
- [ ] don't pollute HOME dir
- [ ] follow XDG spec
- [ ] discuss whether we use the same path on every platform
    - pro: easier DX
    - con: breaks standards? (see [`env-paths`](https://npmjs.com/env-paths))
 - [ ] write tests
    - migrations (generally)
    - migration of config location

**Comment by mixmix** [comment]
PR where this is being discussed: https://github.com/entropyxyz/cli/pull/109#issuecomment-2164859617

**Comment by johnnymatthews** [comment]
I want to make sure that this issue does not get _closed_ when #109 gets merged. This issue is about allowing the user to specify a **custom** location for the config.
