### ISSUE TITLE
[features] feature completeness 

### ISSUE THREAD

**Issue by frankiebee** [entropyxyz/cli#59]
Up for debate:

- [ ] #305
- [ ] #304
- [x] sign should return a hex string not u8a garbage bin
- [x] sign should console.log the verifying key for the signature so that we can provide more context for the signature
- [x] #113

**Comment by rh0delta** [comment]
should we add a new option to allow users to verify the signature returned when signing?

**Comment by frankiebee** [comment]
related to #94

**Comment by frankiebee** [comment]
deffering any new items to the milestone: see : https://github.com/entropyxyz/cli/milestone/3
