### ISSUE TITLE
As a user, when I generate a new key, I'd like to have all information about my newly created key

### ISSUE THREAD

**Issue by vitropy** [entropyxyz/cli#82]
Currently, generating a new key using the CLI produces a single output: the SS58 address of the new account.

```
New account:
{
        name: MyFirstAccount
        address: 5HMnksPMRPqsDqyCj31VoQFgpiswsr12bk2YTyfMUEKCm2bv
        type: seed
}
```

Compare this to Substrate's `subkey` command, which also shows a mnemonic and private information for the generated key:

```
Secret phrase `hotel forest jar hover kite book view eight stuff angle legend defense` is account:
  Secret seed:      0xa05c75731970cc7868a2fb7cb577353cd5b31f62dccced92c441acd8fee0c92d
  Public key (hex): 0xfec70cfbf1977c6965b5af10a4534a6a35d548eb14580594d0bc543286892515
  Account ID:       0xfec70cfbf1977c6965b5af10a4534a6a35d548eb14580594d0bc543286892515
  SS58 Address:     5Hpm9fq3W3dQgwWpAwDS2ZHKAdnk86QRCu7iX4GnmDxycrte
```

What's missing in the CLI output is the secret phrase and the secret seed. Without one (or both?) of those, I feel uncertain about my ability to restore an account key generated by the CLI.

At a minimum, as a user of the CLI, I'd like to have all relevant information about my newly generated key shown to me when I manually create a new account.

**Comment by frankiebee** [comment]
related to #94
